### ISSUE TITLE
initialize error

### ISSUE THREAD

**Issue by ricardo-hl** [LandRover/YowJS#2]
what are the requirements ??

[ 'incoming msg', ConfirmationModel { ID: 'reason' } ]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at Pipe.onread (net.js:564:26)

**Comment by FabsHof** [comment]
+1

**Comment by mzalazar** [comment]
You must edit node_modules/yowjs/src/yowsup/runtime.js and update this function:

```javascript
    getCMDWithArgs() {
        return [
            '-u',
            this.cliPath,
            'demos',
            '-E', // THIS MUST BE ADDED
            's40', // THIS MUST BE ADDED
            '--yowsup',
            '--login',
            this.getCredentials()
        ];
    }
```
